name: Publish and deploy

on:
  workflow_call:
    inputs:
      githubActionsArtifactName:
        required: false
        type: string
        default: maven-artifact
      targetEnv:
        required: true
        type: string
      isProdDevelopment:
        required: true
        type: boolean
      pomArtifactVersion:
        required: true
        type: string
        description: POM Version in semver format
      pomArtifactId:
        required: true
        type: string
    secrets:
      EXCHANGE_CLIENT_ID:
        required: true
      EXCHANGE_CLIENT_SECRET:
        required: true

defaults:
  run:
    shell: bash
    
jobs:

  publish-and-deploy:
    runs-on: ubuntu-latest
    name: Publish and deploy
    environment: ${{ inputs.targetEnv }}
    steps:          
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.githubActionsArtifactName }}  
      
      - name: Get Deployable jar name
        id: getJarName
        run: |
          jarName=`ls *jar`
          echo "Executable Jar name = ${jarName}"
          echo "jarName=$jarName" >> "$GITHUB_OUTPUT"
      
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18.14.0
      
      - name: Setup anypoint CLI
        run: |
          npm install -g anypoint-cli-v4
      
      - name: Publish To Exchange
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
          IS_STABLE_VERSION: ${{ inputs.isProdDevelopment }}
          ASSET_VERSION: ${{ inputs.pomArtifactVersion }}
          ASSET_NAME: ${{ inputs.pomArtifactId }}
          JAR_FILE: ${{ steps.getJarName.outputs.jarName }}
        run: |
          if [[ $IS_STABLE_VERSION == true ]]; then
            assetStatus='published'
          else
            assetStatus='development'
          fi
          anypoint-cli-v4 exchange asset upload $ASSET_NAME/$ASSET_VERSION \
          --type app \
          --files "{\"mule-application.jar\": \"$JAR_FILE\"}" \
          --status $assetStatus
      
      # - name: Deploy to ${{ inputs.targetEnv }}
      #   env:
      #     ANYPOINT_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
      #     ANYPOINT_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
      #     DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
      #     MULE_ENV: ${{ vars.MULE_ENV }}
      #     DEPLOY_TARGET: ${{ vars.DEPLOY_TARGET }}
      #     MAVEN_SETTINGS_SERVER_ID: ${{ vars.MAVEN_SETTINGS_SERVER_ID }}
      #     DEPLOY_REPLICAS: ${{ vars.DEPLOY_REPLICAS }}
      #     DEPLOY_VCORES: ${{ vars.DEPLOY_VCORES }}
      #   run: | 
      #       mvn clean deploy -DskipTests \
      #           -DmuleDeploy \
      #           --settings .github/mvn-config/settings.xml \
      #           -Ddeploy.env=$DEPLOY_ENV \
      #           -Dmule.env=$MULE_ENV \
      #           -Ddeploy.target=$DEPLOY_TARGET \
      #           -Dmvnsettings.serverid=$MAVEN_SETTINGS_SERVER_ID \
      #           -Ddeploy.replicas=$DEPLOY_REPLICAS \
      #           -Ddeploy.vCores=$DEPLOY_VCORES \
      #           -Dexchange.clientId=$EXCHANGE_CLIENT_ID \
      #           -Dexchange.clientSecret=$EXCHANGE_CLIENT_SECRET
            