name: Publish and deploy

on:
  workflow_call:
    inputs:
      githubActionsArtifactName:
        required: false
        type: string
        default: maven-artifact
      targetEnv:
        required: true
        type: string
      isProdDevelopment:
        required: true
        type: boolean
      pomArtifactVersion:
        required: true
        type: string
        description: POM Version in semver format
      pomArtifactId:
        required: true
        type: string
    secrets:
      EXCHANGE_CLIENT_ID:
        required: true
      EXCHANGE_CLIENT_SECRET:
        required: true

defaults:
  run:
    shell: bash
    
jobs:

  publish-and-deploy:
    runs-on: ubuntu-latest
    name: Publish and deploy
    environment: ${{ inputs.targetEnv }}
    steps:          
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.githubActionsArtifactName }}  
      
      - name: Get Deployable jar name
        id: getJarName
        run: |
          jarName=`ls *jar`
          echo "Executable Jar name = ${jarName}"
          echo "jarName=$jarName" >> "$GITHUB_OUTPUT"
      
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18.14.0
      
      - name: Setup anypoint CLI
        run: |
          npm install -g anypoint-cli-v4
      
      - name: Publish To Exchange
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
          IS_STABLE_VERSION: ${{ inputs.isProdDevelopment }}
          ASSET_VERSION: ${{ inputs.pomArtifactVersion }}
          ASSET_NAME: ${{ inputs.pomArtifactId }}
          JAR_FILE: ${{ steps.getJarName.outputs.jarName }}
        run: |
          if [[ $IS_STABLE_VERSION == true ]]; then
            assetStatus='published'
          else
            assetStatus='development'
          fi
          anypoint-cli-v4 exchange asset upload $ASSET_NAME/$ASSET_VERSION \
          --type app \
          --files "{\"mule-application.jar\": \"$JAR_FILE\"}" \
          --status $assetStatus \
          --name $ASSET_NAME
      
      - name: Deploy to ${{ inputs.targetEnv }}
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
          ASSET_VERSION: ${{ inputs.pomArtifactVersion }}
          ASSET_NAME: ${{ inputs.pomArtifactId }}
          DEPLOY_NAME: ${{ inputs.pomArtifactId }}-${{ vars.MULE_ENV }}
          DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
          DEPLOY_TARGET: ${{ vars.DEPLOY_TARGET }}
          DEPLOY_REPLICAS: ${{ vars.DEPLOY_REPLICAS }}
          DEPLOY_VCORES: ${{ vars.DEPLOY_VCORES }}
          DEPLOY_RUNTIME: ${{ vars.DEPLOY_RUNTIME }}
        run: | 
          existingDeployId=$(
            anypoint-cli-v4 runtime-mgr application list --environment Sandbox --output json \
            | jq -r --arg NAME $DEPLOY_NAME --arg TARGET $DEPLOY_TARGET '.[] | select(.name == $NAME and .target.targetId == $TARGET) | .id'
          )
          if [[ -z $existingDeployId ]]; then
            echo 'No existing application found with the name $DEPLOY_NAME in $DEPLOY_TARGET'
            anypoint-cli-v4 \
            runtime-mgr application deploy $DEPLOY_NAME $DEPLOY_TARGET $DEPLOY_RUNTIME $ASSET_NAME  \
            --assetVersion $ASSET_VERSION \
            --environment $DEPLOY_ENV \
            --objectStoreV2 \
            --replicas $DEPLOY_REPLICAS \
            --replicaSize $DEPLOY_VCORES
          else 
          echo "Existing application found with the name $DEPLOY_NAME in $DEPLOY_TARGET; existingDeployId = $existingDeployId"
            anypoint-cli-v4 \
            runtime-mgr application modify $existingDeployId \
            --artifactId $ASSET_NAME \
            --environment $DEPLOY_ENV \
            --assetVersion $ASSET_VERSION \
            --replicas $DEPLOY_REPLICAS \
            --replicaSize $DEPLOY_VCORES
          fi
          